version: '2.1.0.{build}'
image: Visual Studio 2017 Preview
init:
  - git config --global core.autocrlf true
configuration:
  - Debug
environment:
  matrix:  
  - name: FB 3.2
    fb_download: https://www.dropbox.com/s/4o6nvoahmlegv64/binarios.7z?dl=1
cache:
  - '%USERPROFILE%\.nuget\packages -> **\*.csproj'
shallow_clone: true
install:
  - ps: $env:padded_build_number = $env:appveyor_build_number.PadLeft(5, '0')
  # Install .NET Core 2.0
  - ps: Invoke-WebRequest -Uri "https://raw.githubusercontent.com/dotnet/cli/master/scripts/obtain/dotnet-install.ps1" -OutFile "install-dotnet.ps1"
  - ps: .\install-dotnet.ps1 -Version 2.0.3
test: off
before_build:
  - ps: $baseDir = Resolve-Path .
  - dotnet --info
  - appveyor-retry dotnet restore -v Minimal
build_script:
  - ps: $env:build_nuget = 'C:\Program Files\AppVeyor\BuildAgent\Tools\nuget.exe'
after_build:
  - ps: mkdir "$baseDir\out" | Out-Null
  - ps: gci "$baseDir\out" | % { Push-AppveyorArtifact $_.FullName -FileName $_.Name }
before_test:
  - ps: $testsBaseDir = "$baseDir\EFCore.FirebirdSql.FunctionalTests"
  - ps: mkdir C:\firebirdefcore | Out-Null
  - ps: cd C:\firebirdefcore
  - ps: Start-FileDownload "$env:fb_download" | Out-Null
  - ps: 7z x ($env:fb_download -replace '.+/([^/]+)\?dl=1','$1')
  - ps: .\firebird.exe -a
test_script:
  - ps: cd $testsBaseDir
  - ps: dotnet restore
  - ps: dotnet test EFCore.FirebirdSql.FunctionalTests.csproj
notifications:
- provider: GitHubPullRequest
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: true
- provider: Email
  to:
  - ralms@ralms.net
  subject: EntityframeworkCore.FirebirdSql
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: true
